Output asset/demo.gif

Set Shell "zsh"
Set FontSize 12
Set FontFamily "MesloLGS Nerd Font"
Set Width 600
Set Height 800
Set Framerate 24
Set Padding 5



Hide
Type `go run ./cmd/main.go` Enter
Sleep 5

Show

Set TypingSpeed 0.5
Type j
Type j
Type f
Type j
Type f
Sleep 1
Type f
Type g
Sleep 2
Type j
Type ">"
Sleep 2
Type "<"
Type f
Type j
Type j
Type l
Type k
Type k
Type k
Type h

Type '/'
Type 'lett'
Enter
Type g
Sleep 2
Type f
Type `VAR="Escaped"`

